earthquakes:
  outputs:
    dev:
      dataset: earthquake_stg
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: europe-west6
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: earthquake_prod
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: europe-west6
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev