#!/bin/bash
export GCP_PROJECT_ID=dezoomcamp-375819
export GCP_GCS_BUCKET=earthquakes_data_lake_dezoomcamp-375819
export BIGQUERY_DATASET=earthquake_prod
export TMP_BUCKET=dtc_data_lake_dezoomcamp-375819